"""Add global age rules to document

Revision ID: 03b3e71de020
Revises: cb30d365470e
Create Date: 2026-07-31 03:05:15.773547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b3e71de020'
down_revision: Union[str, Sequence[str], None] = 'cb30d365470e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('has_random_age', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('documents', sa.Column('age_roll_min', sa.Integer(), server_default='14', nullable=False))
    op.add_column('documents', sa.Column('age_roll_max', sa.Integer(), server_default='25', nullable=False))
    op.add_column('documents', sa.Column('age_bypass_trait_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'age_bypass_trait_id')
    op.drop_column('documents', 'age_roll_max')
    op.drop_column('documents', 'age_roll_min')
    op.drop_column('documents', 'has_random_age')
    # ### end Alembic commands ###
