"""add category summary and trait subtitle

Revision ID: 284dc95dfb6e
Revises: e4d8169ea230
Create Date: 2026-07-25 20:33:30.974591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '284dc95dfb6e'
down_revision: Union[str, Sequence[str], None] = 'e4d8169ea230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('traits', sa.Column('subtitle', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traits', 'subtitle')
    op.drop_column('categories', 'summary')
    # ### end Alembic commands ###
