"""migrate_to_json_rules

Revision ID: 5e4fc12a2470
Revises: d055a28cf7b9
Create Date: 2026-08-01 22:45:35.967615

"""
from typing import Sequence, Union, Any
import json

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = '5e4fc12a2470'
down_revision: Union[str, Sequence[str], None] = 'd055a28cf7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('rules', sa.JSON(), server_default='[]', nullable=False))
    conn = op.get_bind()
    docs = conn.execute(text("SELECT id, age_bypass_trait_id, gender_bypass_trait_id FROM documents")).fetchall()
    
    # Fetch existing bypasses on categories
    cats = conn.execute(text("SELECT document_id, id AS cat_id, bypass_trait_id, free_pick_trait_id FROM categories")).fetchall()

    discounts = conn.execute(text("""
        SELECT c.document_id, d.source_trait_id, d.target_trait_id, d.discount
        FROM discounts d
        JOIN traits t ON d.target_trait_id = t.id
        JOIN categories c ON t.category_id = c.id
    """)).fetchall()

    rules_by_doc : dict[int, list[dict[str, Any]]] = {doc.id: [] for doc in docs}

    # Process Document Bypasses
    for doc_id, age_bypass, gender_bypass in docs:
        if age_bypass:
            rules_by_doc[doc_id].append({
                "name": "Legacy Age Bypass",
                "ui_context": {"trait_id": age_bypass},
                "conditions": [{"type": "HAS_TRAIT", "targetId": age_bypass}],
                "effects": [{"type": "BYPASS_AGE_ROLL"}]
            })
        if gender_bypass:
            rules_by_doc[doc_id].append({
                "name": "Legacy Gender Bypass",
                "ui_context": {"trait_id": gender_bypass},
                "conditions": [{"type": "HAS_TRAIT", "targetId": gender_bypass}],
                "effects": [{"type": "BYPASS_GENDER_LOCK"}]
            })

    for doc_id, cat_id, bypass, free_pick in cats:
        if bypass:
            rules_by_doc[doc_id].append({
                "name": "Legacy Category Bypass",
                "ui_context": {"trait_id": bypass},
                "conditions": [{"type": "HAS_TRAIT", "targetId": bypass}],
                "effects": [{"type": "BYPASS_CATEGORY_LIMIT", "targetId": cat_id}] 
            })
        if free_pick:
            rules_by_doc[doc_id].append({
                "name": "Legacy Free Pick",
                "ui_context": {"trait_id": free_pick},
                "conditions": [{"type": "HAS_TRAIT", "targetId": free_pick}],
                "effects": [{"type": "FREE_PICK_CATEGORY", "targetId": cat_id}]
            })

    # Process Discounts
    for doc_id, source_id, target_id, discount_pct in discounts:
        multiplier = (100 - discount_pct) / 100.0
        rules_by_doc[doc_id].append({
            "name": "Legacy Discount",
            "ui_context": {"trait_id": source_id},
            "conditions": [{"type": "HAS_TRAIT", "targetId": source_id}],
            "effects": [{"type": "MULTIPLY_COST", "targetId": target_id, "value": multiplier}]
        })

    # Write JSON to database
    for doc_id, rules in rules_by_doc.items():
        conn.execute(
            text("UPDATE documents SET rules = :rules WHERE id = :id"),
            {"rules": json.dumps(rules), "id": doc_id}
        )

    op.drop_table('discounts')
    op.drop_column('categories', 'bypass_trait_id')
    op.drop_column('categories', 'free_pick_trait_id')

    op.drop_column('documents', 'gender_bypass_trait_id')
    op.drop_column('documents', 'age_bypass_trait_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('age_bypass_trait_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('gender_bypass_trait_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'rules')
    op.add_column('categories', sa.Column('free_pick_trait_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('bypass_trait_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('discounts',
    sa.Column('source_trait_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_trait_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('discount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_trait_id'], ['traits.id'], name=op.f('discounts_source_trait_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_trait_id'], ['traits.id'], name=op.f('discounts_target_trait_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_trait_id', 'target_trait_id', name=op.f('discounts_pkey'))
    )
    # ### end Alembic commands ###
