"""Baseline schema

Revision ID: 68594250f176
Revises: 
Create Date: 2026-07-21 03:06:20.735426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68594250f176'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('choice_points', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('jumpers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jumpers_id'), 'jumpers', ['id'], unique=False)
    op.create_table('drawbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('profit', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drawbacks_id'), 'drawbacks', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_table('origins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_origins_id'), 'origins', ['id'], unique=False)
    op.create_table('perks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perks_id'), 'perks', ['id'], unique=False)
    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jumper_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('selected_origin_id', sa.Integer(), nullable=True),
    sa.Column('remaining_cp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jumper_id'], ['jumpers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_origin_id'], ['origins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builds_id'), 'builds', ['id'], unique=False)
    op.create_table('drawback_locked_origins',
    sa.Column('drawback_id', sa.Integer(), nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drawback_id'], ['drawbacks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_id'], ['origins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('drawback_id', 'origin_id')
    )
    op.create_table('origin_perk_discounts',
    sa.Column('origin_id', sa.Integer(), nullable=False),
    sa.Column('perk_id', sa.Integer(), nullable=False),
    sa.Column('discount_percentage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['origin_id'], ['origins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['perk_id'], ['perks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('origin_id', 'perk_id')
    )
    op.create_table('build_drawbacks',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('drawback_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drawback_id'], ['drawbacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('build_id', 'drawback_id')
    )
    op.create_table('build_items',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('build_id', 'item_id')
    )
    op.create_table('build_perks',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('perk_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['perk_id'], ['perks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('build_id', 'perk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('build_perks')
    op.drop_table('build_items')
    op.drop_table('build_drawbacks')
    op.drop_table('origin_perk_discounts')
    op.drop_table('drawback_locked_origins')
    op.drop_index(op.f('ix_builds_id'), table_name='builds')
    op.drop_table('builds')
    op.drop_index(op.f('ix_perks_id'), table_name='perks')
    op.drop_table('perks')
    op.drop_index(op.f('ix_origins_id'), table_name='origins')
    op.drop_table('origins')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_drawbacks_id'), table_name='drawbacks')
    op.drop_table('drawbacks')
    op.drop_index(op.f('ix_jumpers_id'), table_name='jumpers')
    op.drop_table('jumpers')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
