"""removed has cost

Revision ID: 7cb89de86d8a
Revises: 5e4fc12a2470
Create Date: 2026-08-02 19:47:41.487303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb89de86d8a'
down_revision: Union[str, Sequence[str], None] = '5e4fc12a2470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'has_cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('has_cost', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
