"""add jumper and build tables

Revision ID: 8c64d67facd3
Revises: add167a5e6f9
Create Date: 2026-07-28 03:48:04.047542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c64d67facd3'
down_revision: Union[str, Sequence[str], None] = 'add167a5e6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_traits',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('trait_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trait_id'], ['traits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('build_id', 'trait_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('build_traits')
    # ### end Alembic commands ###
