"""add category sort_order

Revision ID: 8e1fd068ea1e
Revises: 284dc95dfb6e
Create Date: 2026-07-25 22:37:15.037878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1fd068ea1e'
down_revision: Union[str, Sequence[str], None] = '284dc95dfb6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'sort_order')
    # ### end Alembic commands ###
