"""add trait is_modifier flag

Revision ID: 9a057aa95926
Revises: 8e1fd068ea1e
Create Date: 2026-07-26 01:05:59.365073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a057aa95926'
down_revision: Union[str, Sequence[str], None] = '8e1fd068ea1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traits', sa.Column('is_modifier', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traits', 'is_modifier')
    # ### end Alembic commands ###
