"""Add wildcard trait support

Revision ID: 9dba69183ea9
Revises: a247068b89d9
Create Date: 2026-07-30 05:58:01.291990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dba69183ea9'
down_revision: Union[str, Sequence[str], None] = 'a247068b89d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('free_pick_trait_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'free_pick_trait_id')
    # ### end Alembic commands ###
