"""Add force random and bypass traits to categories

Revision ID: a247068b89d9
Revises: 8c64d67facd3
Create Date: 2026-07-30 05:37:22.708970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a247068b89d9'
down_revision: Union[str, Sequence[str], None] = '8c64d67facd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_random', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('categories', sa.Column('bypass_trait_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'bypass_trait_id')
    op.drop_column('categories', 'is_random')
    # ### end Alembic commands ###
