"""add max allowed count to categories

Revision ID: add167a5e6f9
Revises: 9a057aa95926
Create Date: 2026-07-26 02:45:51.346231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add167a5e6f9'
down_revision: Union[str, Sequence[str], None] = '9a057aa95926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('max_allowed', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'max_allowed')
    # ### end Alembic commands ###
