"""Add mandatory age to jumpers and builds

Revision ID: cb30d365470e
Revises: 9dba69183ea9
Create Date: 2026-07-31 02:28:25.786903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb30d365470e'
down_revision: Union[str, Sequence[str], None] = '9dba69183ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builds', sa.Column('age', sa.Integer(), server_default='18', nullable=False))
    op.add_column('jumpers', sa.Column('age', sa.Integer(), server_default='18', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jumpers', 'age')
    op.drop_column('builds', 'age')
    # ### end Alembic commands ###
