"""Add gender to jumper, documents, and builds

Revision ID: d055a28cf7b9
Revises: 03b3e71de020
Create Date: 2026-08-01 04:55:01.549881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd055a28cf7b9'
down_revision: Union[str, Sequence[str], None] = '03b3e71de020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builds', sa.Column('gender', sa.String(length=50), server_default='Unknown', nullable=False))
    op.add_column('documents', sa.Column('gender_bypass_trait_id', sa.Integer(), nullable=True))
    op.add_column('jumpers', sa.Column('gender', sa.String(length=50), server_default='Unknown', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jumpers', 'gender')
    op.drop_column('documents', 'gender_bypass_trait_id')
    op.drop_column('builds', 'gender')
    # ### end Alembic commands ###
